### ISSUE TITLE
Benefit "Extensible and Hackable" has a bit of negative connotation because of hackable in it. Can that be replaced by some other word?

### ISSUE THREAD

**Issue by Priyaag** [getgauge/documentation#13]
Page: "http://getgauge.io/documentation/user/current/"
Section: Why Gauge?
Point no. 6: Extensible through Plugins and Hackable

I know that in the context of framework, hackable means that its customizable, but I also think that it has a negative connotation to it, especially for QAs.

**Comment by Thunderforge** [comment]
I think that the intention was to make "hackable" mean "able to be tinkered with", much like how a [hackerspace](https://en.wikipedia.org/wiki/Hackerspace) is a location where people work on technical projects. Admittedly, it's probably a more developer-oriented term than a business-oriented term.

The only word I can think of that would serve as a replacement would be "customizable", but that sounds like a much weaker word. I guess shortening it to "Extensible through Plugins" would be sufficient. Of the two, I'd prefer the latter.

**Comment by kaustavdm** [comment]
I agree with @Thunderforge. The concern of that @Priyaag has mentioned is related to the general misconception and misuse of the term "hacking". When we say hackable, it is intended to mean "playful cleverness" ([ref](https://stallman.org/articles/on-hacking.html)), not "unauthorized access".

**Comment by Thunderforge** [comment]
Since this is, as @kaustavdm said, "related to the general misconception and misuse of the term "hacking"", I would be in favor of changing the word or phrase.

**Comment by kaustavdm** [comment]
@Thunderforge To clarify my previous comment &mdash; when I said I agreed with your comment, I meant I agree with the part about "able to be tinkered with". I did not mean that I would like to stop using the term "hackable" and replace it with something else. The term "hackable", when used according to the intended meaning, still conveys exactly what we want Gauge to be.

That is my opinion. I'll leave it to others to decide whether it is actually needs changing or not.

**Comment by Thunderforge** [comment]
@BugDiver What were the reasons that this was rejected?
