### ISSUE TITLE
Introduction line of XML Report plugin page should be improved.

### ISSUE THREAD

**Issue by Priyaag** [getgauge/documentation#16]
Page: http://getgauge.io/documentation/user/current/plugins/xml_report_plugin.html

Problem: Introduction statement "Gauge plugin to generate JUnit style XML reports in the format described here" doesn't make complete sense. Also, Gauge is linking to github, but I am not sure if thats the intent.

**Comment by sriv** [comment]
Docs have been updated. Please check [here](http://getgauge.io/documentation/user/current/reporting_features/xml_report_plugin.html)
