### ISSUE TITLE
more info is required when use data table with external csv file

### ISSUE THREAD

**Issue by uzmar** [getgauge/documentation#17]
There is no explanation how to use csv file i.e. 
1. csv should be with header columns or not ?
2.There is one csv file  in example project for Visual Studio,that is without header- (that is not working)

**Comment by kashishm** [comment]
> 1. csv should be with header columns or not ?

Added the example and structure information of csv in documentation

> 2.There is one csv file in example project for Visual Studio,that is without header- (that is not working)

Logged an issue in [gauge-example-csharp#3](https://github.com/getgauge/gauge-example-csharp/issues/3)
