### ISSUE TITLE
 remove wrong parameter in multiple step java example 

### ISSUE THREAD

**Issue by cluelessjoe** [getgauge/documentation#30]
More details there: https://github.com/cluelessjoe/documentation/commit/f460a75fc83d3f6b805bee6fbbd529ee4de041a7

cheers :)

**Comment by mahendrakariya** [comment]
@cluelessjoe Thanks a lot for reporting this! Could you please send us a pull request with your changes?

**Comment by cluelessjoe** [comment]
Pull request done, cf issue #31 

:)
