### ISSUE TITLE
Update IntelliJ docs for multiple files in run config

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/documentation#51]
The delimiter for multiple spec files in run config has been changed from `,` to `||` due to https://github.com/getgauge/Intellij-Plugin/issues/101. This should be updated in the docs.

We also need to mention that this is a breaking change. Until v0.1.0 of IntelliJ plugin, the delimiter is `,`. Any higher version will have delimiter `||`.

**Comment by sriv** [comment]
This issue was moved to getgauge/docs.getgauge.io#20
