### ISSUE TITLE
More clarification for table parameter

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/documentation#53]
On the table params page http://getgauge.io/documentation/user/current/gauge_terminologies/parameters/table_parameters.html
- [ ] At the top of the page, we start with `Table Parameters can be used in two ways`. Bullet should be removed from this line.
- [ ] On this page, it's very difficult to find how a user can pass table as a param to step. I think someone new to Gauge will struggle a lot figuring this out. We should add more details about it.
- [ ] Data driven execution should be mentioned at the end since it's a slightly advanced topic. The docs on this page should start with table param that can be passed to step.
- [ ] There are no docs which says data table at spec level can also be passed from external sources. Should Data table driven scenarios be explained under `Param` section or `Execution` section? 

I also have a question. Will it be correct to call the table at the top of the spec as a `param`? We are not passing it as an arg to the step implementation. Personally, I feel it is not a param.

**Comment by sriv** [comment]
This issue was moved to getgauge/docs.getgauge.io#21
