### ISSUE TITLE
Inconsistent formatting

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/documentation#54]
In the [further reading](http://getgauge.io/documentation/user/current/gauge_terminologies/steps.html) section on the [steps](http://getgauge.io/documentation/user/current/gauge_terminologies/steps.html) page, formatting is inconsistent. The first two bullet points use small case, while the rest of them use sentence case. We should be consistent and use sentence case for every bullet point.

This may be the case even on other pages. I just happened to notice this on steps page.

**Comment by BugDiver** [comment]
Changes have been made through [this](https://github.com/getgauge/documentation/commit/b3572b8ffe12cde3373297ee004cc3ff8f1751ba) commit.
