### ISSUE TITLE
Redundant files

### ISSUE THREAD

**Issue by BugDiver** [getgauge/documentation#55]
There are a bunch of files in `language_features` folder. Seems like these files are not being used. I am not sure if these are still needed.

@sguptatw or @kaustavdm Could one of you please confirm and delete these files if they are redundant?

**Comment by kaustavdm** [comment]
@BugDiver Do you mean they are written, but are not part of the book's index?

**Comment by mahendrakariya** [comment]
I think what he means is that the [`language_features`](https://github.com/getgauge/documentation/tree/master/user/language_features) folder still has individual files for each language for certain features like execution hooks, data stores, etc. We have moved to code tabs layout. Do we still need separate doc files for each language?

**Comment by kaustavdm** [comment]
No we don't need them. But, let's not clean them up straight away, till we are absolutely certain that their contents have been completely moved. Once they have been moved, we can place a redirect, if necessary.

**Comment by mahendrakariya** [comment]
Cool. The only thing is that the HTML files will be generated for every md file. And certain links in these old files are not updated. So they continue throwing 404. Having too many 404s will result in page rank penalty.

So maybe for the time being, we should find out some way to exclude the HTML generation of such redundant files.

That said, we should look forward to deleting them at the earliest. Dead code (files) is always a tech debt.

**Comment by kaustavdm** [comment]
AFAIK, if those files are not part of `SUMMARY.md`, they will not be generated as HTML, irrespective of whether they are in the folder or not.

**Comment by kaustavdm** [comment]
There is one file, [`language_features/step_name_template.md`](https://github.com/getgauge/documentation/blob/master/user/language_features/step_name_template.md), that is not part of `SUMMARY.md` but is linked to from [`troubleshooting/execution.md`](https://github.com/getgauge/documentation/blob/master/user/troubleshooting/execution.md). Should it be retained? If yes, where should be moved to in the documentation hierarchy?

@getgauge/core: Suggestions?

**Comment by BugDiver** [comment]
The file ```step_name_template.md``` has been removed. ```troubleshooting/execution.md``` now links to ```step_implemetstions.md```.
