### ISSUE TITLE
Incomplete code snippet for exec hooks - ruby

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/documentation#57]
On the execution hooks page, Ruby doesn't have code snippets for all hooks like Java and C#.

http://getgauge.io/documentation/user/current/language_features/execution_hooks.html

**Comment by BugDiver** [comment]
Changes have been made through [this](https://github.com/getgauge/documentation/commit/95e8863a2312bc08e7964be8cbeecfe824959a8b) commit.
