### ISSUE TITLE
Merge and improve environment variables (configuration) docs

### ISSUE THREAD

**Issue by kaustavdm** [getgauge/documentation#61]
Currently, details on environment variables (configuration options) for Gauge core and runners are spread across 2 different sections, without any internal linking. Also, they are incomplete.

**Proposal:**
- [ ] Merge ["Language Features > Configuration"](http://getgauge.io/documentation/user/current/language_features/configuration.html) into ["Advanced Readings > Gauge Configuration"](http://getgauge.io/documentation/user/current/advanced_readings/configuration/).
- [ ] Rename: "Advanced Readings > Gauge Configuration" to "Advanced Readings > Configuration"
- [ ] Add language specific configuration options as sub-articles to "Advanced Readings > Configuration".

**Comment by sriv** [comment]
This issue was moved to getgauge/docs.getgauge.io#22
