### ISSUE TITLE
Getting 404 page on this link

### ISSUE THREAD

**Issue by sguptatw** [getgauge/documentation#65]
_From @shashisd on August 9, 2016 13:47_

http://getgauge.io/documentation/user/current/getting_started/project_structure/configuration.md 

### Expected behavior

Tell us what should happen
### Actual behavior

Tell us what happens instead
### Steps to reproduce

1.
2.
3.
### Gauge version

```
Run gauge -v on your system and paste the results here.
```

_Copied from original issue: getgauge/gauge#498_

**Comment by sguptatw** [comment]
@shashisd : Thank you for reporting the issue.
This page is currently available at /documentation/user/current/getting_started/project_structure/

We are looking into the issue of redirecting the user to the new page automatically.

**Comment by sguptatw** [comment]
Accessing http://getgauge.io/documentation/user/current/getting_started/project_structure/configuration.md
is giving the redirecting message but not going to the new page.

**Comment by kaustavdm** [comment]
@sguptatw This is a result of invalid redirect configuration in https://github.com/getgauge/documentation/blob/master/user/redirects.json#L23. The `from` field should end in `.html`.

**Comment by BugDiver** [comment]
this page is currently available [here](http://getgauge.io/documentation/user/current/getting_started/project_structure/).
