### ISSUE TITLE
Incomplete feature documentation on Visual studio

### ISSUE THREAD

**Issue by sguptatw** [getgauge/documentation#66]
Refactoring documentation is not present in [Visual Studio features](http://getgauge.io/documentation/user/current/ide_support/visual_studio_features.html)
Formatting documentation is not present in [Visual Studio features](http://getgauge.io/documentation/user/current/ide_support/visual_studio_features.html)
For Parallel execution it will be good if we can add a link to the existing article and mention there is support from the command line.
Will also be helpful if the documentation has content links like the one in [IntelliJ](http://getgauge.io/documentation/user/current/ide_support/features.html#parallel-execution).

**Comment by sriv** [comment]
This issue was moved to getgauge/docs.getgauge.io#23
