### ISSUE TITLE
A couple of dead links in related to Execution hooks

### ISSUE THREAD

**Issue by RPrimrose** [getgauge/documentation#75]
I noticed a couple of broken links to the "Execution Hooks" section. 

http://getgauge.io/documentation/user/current/advanced_readings/execution_hooks/context.html and http://getgauge.io/documentation/user/current/advanced_readings/execution_hooks/filtering.html each have a "hooks" link that goes to http://getgauge.io/documentation/user/language_features/execution_hooks.md, which 404's.

Presumably they should point to  http://getgauge.io/documentation/user/current/language_features/execution_hooks.html instead.

**Comment by sriv** [comment]
@bugdiver - are there any more changes pending? If not, can this be closed?

Thanks @RPrimrose for letting us know!

**Comment by BugDiver** [comment]
@sriv I fixed the links pointed by @RPrimrose. I also used some broken link checkers but because of redirections I din't get a valid response. I think it's done but we should find some nice link checker to validate all the links.

**Comment by sriv** [comment]
Might be well worth putting it in our build pipeline.

**Comment by sriv** [comment]
This issue was moved to getgauge/docs.getgauge.io#25
