### ISSUE TITLE
Unwanted spaces gives wrong usage in the tags of maven and gradle

### ISSUE THREAD

**Issue by sguptatw** [getgauge/documentation#78]
Additional Properties of [maven](https://docs.getgauge.io/configuration.html#all-additional-properties) and [gradle](https://docs.getgauge.io/configuration.html#id7)

This gives the wrong usage.

**Comment by sriv** [comment]
This issue was moved to getgauge/docs.getgauge.io#3

**Comment by sriv** [comment]
wrong repo. moving it to the correct one.
